version: '3.8'

services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
  
  # initial_admin_password:
  #   image: busybox
  #   container_name: initial_admin_password
  #   volumes:
  #     - ./jenkins_home:/var/jenkins_home
  #   command: cp /var/jenkins_home/secrets/initialAdminPassword /var/www/html/initialAdminPassword

  mysqldb:
    container_name: db
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=myDevDb
      - DATABASE_URL="mysql://dbuser:dbpass@mysqldb:3306/myDevDb"
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
      - ./src/databases/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./prisma/migrations/20240205085842_my_init/migration.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      
  node-api:
    container_name: api
    depends_on:
      - mysqldb     
    build: .
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DATABASE_URL=$DATABASE_URL
    ports:
      - 5000:5000

volumes: 
  db:
  jenkins_home:
    

  

    
      