version: '3.8'

services:

  mysqldb:
    container_name: db
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=myDevDb
      - DATABASE_URL="mysql://dbuser:dbpass@mysqldb:3306/myDevDb"
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
      - ./src/databases/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./prisma/migrations/20240205085842_my_init/migration.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      
  node-api:
    container_name: api
    depends_on:
      - mysqldb     
    build: .
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DATABASE_URL=$DATABASE_URL
    ports:
      - 5000:5000

volumes: 
  db:

    

  

    
      